### ISSUE TITLE
CUDA error always at the same point

### ISSUE THREAD

**Issue by smithee771** [shirgur/hp-vae-gan#3]
Hi, first of all thanks for sharing your code :)

I'm running COLAB notebook with a short video (2 secs). When I run 

_!python /content/hp-vae-gan/train_video_baselines.py --video-path /content/movie-2secs.mp4 --checkname mymovie--visualize --generator GeneratorSG --train-depth 1_

I always get this error in step 10, no matter the number of iterations (I've lowered to 50 in this example):

_RuntimeError: CUDA out of memory. Tried to allocate 270.00 MiB (GPU 0; 15.90 GiB total capacity; 14.64 GiB already allocated; 49.88 MiB free; 14.94 GiB reserved in total by PyTorch)
Training scale [10/10]:   0% 0/50_ 

Is this an error? Can I tweak something to make this work? Many thanks in advance

**Comment by shirgur** [comment]
Try lowering the maximum video/image size
Results for scales 1 - 9 will be visible in tensorboard (logs)
We use 32GB GPU in our experiments- though 16GB GPUs are also fine when using our model
